### PR TITLE
Fix issues in virtio_net

### LINKED ISSUE #64: netserver hangs under TCP_STREAM test
I'm running `netserver` and `netperf` (version 2.7.0, built from the source on netperf's site) as follows:

```
## Server
➜  lkl git:(passive-open) ✗ sudo LKL_HIJACK_NET_TAP=eth0 LKL_HIJACK_NET_IP=192.168.13.2  LKL_HIJACK_NET_NETMASK_LEN=1 LKL_HIJACK_DEBUG=1 taskset -c 10 bin/lkl-hijack.sh netserver -L 192.168.13.2 -d -v 99 -D -f

## Client
➜  lkl git:(passive-open) ✗ netperf -H 192.168.13.2 -t TCP_STREAM -l 1
```

The test runs fine for a while, but it eventually says:

```
[ 3625.088000] virtio_net virtio0: input.0:id 24 is not a head!
```

and hangs forever. `tcpdump` on the interface shows that packets go back and forth normally until LKL stops ack-ing part way through, the sender retries a few times, then starts sending out ARP requests to find out where the host has gone with no response. Looking at it under `gdb` shows that the `netserver` thread is blocked on a `recv` call, and LKL continues to spin up and kill worker threads periodically. `strace` shows that it continues polling the fd associated with the TAP device. `TCP_RR` tests with the same options work fine.

I had to make some changes to the host's routing table to get it to force it not to go through `lo`, the relevant info is:

```
➜  lkl git:(passive-open) ✗ ip addr
2: em1: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    ....
    inet 172.x.y.z/q brd ??.??.??.?? scope global em1
       valid_lft forever preferred_lft forever
861: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 500
    link/ether f2:e4:2a:59:2b:03 brd ff:ff:ff:ff:ff:ff
    inet 192.168.13.1/24 scope global eth0
       valid_lft forever preferred_lft forever
    ...
➜  lkl git:(passive-open) ✗ ip route
...
192.168.13.1 dev eth0  scope link  src 172.x.y.z
192.168.13.2 dev eth0  scope link  src 172.x.y.z 
```

What might be going on here?

### PR DESCRIPTION
**Pull request by pscollins**
This PR closes #64. 

@opurdila I'm not sure how to handle the issue with `free_mem` properly -- I left that as is because I think it will be easier to do after #86 is merged. It seems harmless enough to me to hold on to that memory until LKL exits, but let me know how you want that to be handled.

[Review on Reviewable](https://reviewable.io/reviews/lkl/linux/87)

### CODE REVIEW

**Comment by opurdila** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[arch/lkl/kernel/setup.c, line 153 \[r1\]](https://reviewable.io:443/reviews/lkl/linux/87#-KBEub3iDbVmP6xdskHU:-KBEub3iDbVmP6xdskHV:683793685) ([raw file](https://github.com/lkl/linux/blob/e9f37b575136febeb738d54f9d24563b8f74b4a1/arch/lkl/kernel/setup.c#L153)):*
Yes, we need a way to shutdown non-kernel helper threads. I agree that this is probably best resolved after we merge DPDK.

---

*[tools/lkl/lib/virtio.c, line 64 \[r1\]](https://reviewable.io:443/reviews/lkl/linux/87#-KBErQA1j_Kp-HnvUKbg:-KBErQA2Ut1Fbpdvn-D8:-546368955) ([raw file](https://github.com/lkl/linux/blob/e9f37b575136febeb738d54f9d24563b8f74b4a1/tools/lkl/lib/virtio.c#L64)):*
This is not needed, lkl_trigger_irq already uses a __sync_fetch operations which implies a full memory barrier.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/lkl/linux/87)*

**Comment by pscollins** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[arch/lkl/kernel/setup.c, line 153 \[r1\]](https://reviewable.io:443/reviews/lkl/linux/87#-KBEub3iDbVmP6xdskHU:-KBF28l3FUvy5dwHu4Pl:2117278183) ([raw file](https://github.com/lkl/linux/blob/e9f37b575136febeb738d54f9d24563b8f74b4a1/arch/lkl/kernel/setup.c#L153)):*
SGTM, I'll leave it as is for now.

---

*[tools/lkl/lib/virtio.c, line 64 \[r1\]](https://reviewable.io:443/reviews/lkl/linux/87#-KBErQA1j_Kp-HnvUKbg:-KBF2BF3_RNqbtV9DZBI:1794731161) ([raw file](https://github.com/lkl/linux/blob/e9f37b575136febeb738d54f9d24563b8f74b4a1/tools/lkl/lib/virtio.c#L64)):*
Great!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/lkl/linux/87)*

File: tools/lkl/lib/virtio_net.c [hunk 1]
```diff
@@ -76,15 +114,47 @@ void poll_thread(void *arg)
...
+	struct lkl_mutex_t **ret = lkl_host_ops.mem_alloc(
+		sizeof(struct lkl_mutex_t*) * num_queues);
+	if (!ret)
+		return NULL;
+
+	memset(ret, 0, sizeof(struct lkl_mutex_t*) * num_queues);
+	for (i = 0; i < num_queues; i++) {
+		ret[i] = lkl_host_ops.mutex_alloc();
+		if (!ret[i]) {
+			free_queue_locks(ret, num_queues);
```
Comment (stfairy) [inline tools/lkl/lib/virtio_net.c]: I guess you can pass `i` instead of `num_queues` so you don't need to do the `memset`?

File: tools/lkl/lib/virtio_net.c [hunk 2]
```diff
@@ -105,22 +175,26 @@ int lkl_netdev_add(union lkl_netdev nd, void *mac)
...
-	dev->tx_poll.sem = lkl_host_ops.sem_alloc(0);
 	dev->tx_poll.dev = dev;
 
-	if (!dev->rx_poll.sem || !dev->tx_poll.sem)
-		goto out_free;
+	/* MUST match the number of queue locks we initialized. We
+	 * could init the queues in virtio_dev_setup to help enforce
+	 * this, but netdevs are the only flavor that need these
+	 * locks, so it's better to do it here. */
+	ret = virtio_dev_setup(&dev->dev, NUM_QUEUES, 32);
```
Comment (stfairy) [inline tools/lkl/lib/virtio_net.c]: Maybe give 32 a name?

File: tools/lkl/lib/virtio_net.c (hunk 1 above)
Comment (pscollins) [inline tools/lkl/lib/virtio_net.c]: Done

File: tools/lkl/lib/virtio_net.c (hunk 2 above)
Comment (pscollins) [inline tools/lkl/lib/virtio_net.c]: Done
