### PR TITLE
lkl tools: cpfromfs: fix root directory copy

### LINKED ISSUE #295: cpfromfs seems to inject unpredictable prefix into filesystem
I ran the following commands:

```shell
cptofs -P 1 -t ext4 -i test.img ~/linux /
cpfromfs -P 1 -t ext4 -i test.img / ~/linuxcopy
```

Which leads to the following in `~/linuxcopy`:

```
/home/ec2-user/linuxcopy
└── 0000fe01
    ├── linux
    │   ├── arch
...
```

I think that `0000fe01` is an implementation detail of `cptofs` and shouldn't appear in the output. Furthermore I don't think it's constant, so I can't just ask `cpfromfs` to copy starting from that mount point.

### PR DESCRIPTION
**Pull request by tavip**
This fixes #295

---
This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/300)

### CODE REVIEW

File: tools/lkl/cptofs.c [hunk 1]
```diff
@@ -493,6 +493,9 @@ int copy_one(const char *src, const char *mpoint, const char *dst)
 		snprintf(dst_path, sizeof(dst_path),  "%s", dst);
 	}
 
+	if (strcmp(src, "/") == 0)
```
Comment (copumpkin) [inline tools/lkl/cptofs.c]: Is it worth handling `"//"` and other logically equivalent paths here? I don't expect to use them directly, but they can occasionally arise when someone uses programmatically generated paths.

Comment (tavip) [inline tools/lkl/cptofs.c]: @copumpkin Good point. I think the equivalent regular expression [./]* should cover all cases. .. already works fine so we don't need consider it. Anything else?

Comment (tavip) [inline tools/lkl/cptofs.c]: @copumpkin done

File: tools/lkl/cptofs.c [hunk 2]
```diff
@@ -480,6 +480,19 @@ static int searchdir(const char *src, const char *dst, const char *match)
 	return ret;
 }
 
+static int match_root(const char *src)
+{
+	const char *c = src;
+
+	while (*c) {
+		if (*c != '.' && *c != '/')
```
Comment (copumpkin) [inline tools/lkl/cptofs.c]: Just FYI, this will match "../" and "/../../../....." and other nonsense like that too. That's why I phrased my original comment as a question, FWIW: not sure it's actually worth doing this accurately 😄

**Comment by copumpkin** [comment]
Sorry, haven't had a chance to test this yet, but the approach looks good code-wise!

**Comment by tavip** [comment]
@copumpkin Pushed a new version, probably still has multiple holes in it :) but unless there is something really wrong with it, I think it is good enough.
