### PR TITLE
lkl: Android ARM (arm/arm64) support

### LINKED ISSUE #59: Android ARM support
I would like to use LKL in an Android app, so I added `elf32-littlearm` as a supported POSIX output format in the Makefiles and attempted to build with a standalone `arm-linux-androideabi` toolchain, but I get this:

```
arm-linux-androideabi-gcc -Iinclude -Wall -g -O2 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -fno-strict-aliasing -fPIC -c -o lib/net.o lib/net.c
In file included from /home/david/Android/toolchains/arm-linux-androideabi-4.9-21/sysroot/usr/include/linux/signal.h:21:0,
                 from /home/david/Android/toolchains/arm-linux-androideabi-4.9-21/sysroot/usr/include/signal.h:48,
                 from /home/david/Android/toolchains/arm-linux-androideabi-4.9-21/sysroot/usr/include/sys/select.h:35,
                 from /home/david/Android/toolchains/arm-linux-androideabi-4.9-21/sysroot/usr/include/unistd.h:34,
                 from include/lkl/linux/shm.h:6,
                 from include/lkl/asm/syscalls.h:81,
                 from include/lkl.h:6,
                 from include/lkl_host.h:5,
                 from lib/net.c:5:
include/lkl/asm-generic/signal.h:103:22: error: expected ':', ',', ';', '}' or '__attribute__' before '.' token
  __lkl__sighandler_t sa_handler;
                      ^
<builtin>: recipe for target 'lib/net.o' failed
make: *** [lib/net.o] Error 1
```

I'm not a kernel developer at all, so I don't really know where to go from here.

### PR DESCRIPTION
**Pull request by thehajime**
Initial attempt to run an application with hijack library on Android
platform.  Tested mostly on Android 6.x and 7.x.

The build process assumes that the android ndk toolchain is installed in
a host system as circle.yml does in its test.  arm32 build uses
alternate linker, stored in tools/lkl/bin directory, in order to avoid
the link issue (issue #59).

The CircleCI test infrastructure requires to use ubuntu 14.04 for this
test.

* Limitations
- aarch64 isn't tested on circleci due to difficulties on aarch64
emulator.
- bionic libc on android-24 emulator (arm32) doesn't call destructor, so
some of tests in hijack-test.sh fail.
- net.sh doesn't properly test network related issue.

Fixes #59.

Signed-off-by: Hajime Tazaki <thehajime@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/lkl/linux/372)

### CODE REVIEW

**Comment by thehajime** [comment]
Cc: @mix1

**Comment by thehajime** [comment]
```
ERROR: do not set execute permissions for source files
#255: FILE: tools/lkl/bin/arm-linux-androideabi-ld.gold
```

I hope the above error isn't problematic.

**Comment by thehajime** [comment]
I rebased the branch.  It'll be great if somebody gives a review.

File: tools/lkl/Makefile [hunk 1]
```diff
@@ -69,7 +70,7 @@ ifneq (,$(filter $(OUTPUT_FORMAT),elf64-x86-64 elf32-i386 elf64-x86-64-freebsd e
   # Virtual Distributed Ethernet configuration
   ifeq ($(vde),yes)
     export CONFIG_AUTO_LKL_VIRTIO_NET_VDE=y
-    CFLAGS     += -DCONFIG_AUTO_LKL_VIRTIO_NET_VDE
+    CFLAGS     += -DCONFIG_AUTO_LKL_VIRTIO_NET_VDE $(shell pkg-config --cflags vdeplug)
```
Comment (tavip) [inline tools/lkl/Makefile]: I think CFLAGS is already updated in lib/Kbuild? Maybe you can pick up this commit:

https://github.com/tavip/linux/commit/20ed06560794f99fdcb6beaf0c764d60f1ecd0b5
 
and since it fixes errors when vde is not installed on the host and removes ifdef from the test.

File: tools/lkl/lib/hijack/hijack.c [hunk 2]
```diff
@@ -222,6 +229,10 @@ int ioctl(int fd, unsigned long req, ...)
 }
 
 
+#if defined(__ANDROID__) && __LKL__BITS_PER_LONG == 32
+#define __lkl__NR_fcntl __lkl__NR_fcntl64
```
Comment (tavip) [inline tools/lkl/lib/hijack/hijack.c]: We can move this to tools/lkl/include/lkl.h.

File: tools/lkl/lib/virtio_net_vde.c [hunk 3]
```diff
@@ -1,6 +1,6 @@
+#include <stdio.h>
 #ifdef CONFIG_AUTO_LKL_VIRTIO_NET_VDE
```
Comment (tavip) [inline tools/lkl/lib/virtio_net_vde.c]: Need to change this to CONFIG_AUTO_POSIX_LKL.

File: arch/lkl/include/uapi/asm/swab.h [hunk 4]
```diff
@@ -0,0 +1,10 @@
+#ifndef _ASM_LKL_SWAB_H
```
Comment (tavip) [inline arch/lkl/include/uapi/asm/swab.h]: We also need to remove swab.h from Kbuild

File: tools/lkl/Makefile (hunk 1 above)
Comment (thehajime) [reply tools/lkl/Makefile]: This portion tries to do the same with your commit (tavip/linux@20ed065), indeed.
and much complete solution including net-test fix, etc.

I will pull (cherry-pick) your commit in this PR.

File: tools/lkl/lib/hijack/hijack.c (hunk 2 above)
Comment (thehajime) [reply tools/lkl/lib/hijack/hijack.c]: agree.  will fix this.

File: tools/lkl/lib/virtio_net_vde.c (hunk 3 above)
Comment (thehajime) [reply tools/lkl/lib/virtio_net_vde.c]: I think CONFIG_AUTO_LKL_VIRTIO_NET_VDE should be okay as your commit (https://github.com/tavip/linux/commit/20ed06560794f99fdcb6beaf0c764d60f1ecd0b5) does, no ?

File: arch/lkl/include/uapi/asm/swab.h (hunk 4 above)
Comment (thehajime) [reply arch/lkl/include/uapi/asm/swab.h]: Does this diff (https://github.com/lkl/linux/pull/372/files#diff-051aff7b50396c2ae5a000bd891b5fc3) do the job you mentioned here ?

File: tools/lkl/lib/virtio_net_vde.c (hunk 3 above)
Comment (tavip) [reply tools/lkl/lib/virtio_net_vde.c]: you are right :)

Comment (thehajime) [reply tools/lkl/lib/virtio_net_vde.c]: okay

File: arch/lkl/include/uapi/asm/swab.h (hunk 4 above)
Comment (thehajime) [reply arch/lkl/include/uapi/asm/swab.h]: okay, thanks.

**Comment by thehajime** [comment]
I've updated this patchset.  The jenkins test should fail due to checkpatch error (circleci instance on my account is now disabled this check).

Hope other tests are also fine (finger crossed).

File: tools/lkl/include/lkl.h [hunk 5]
```diff
@@ -19,6 +19,10 @@ extern "C" {
 #define strtok_r strtok_s
 #endif
 
+#if defined(__ANDROID__) && __LKL__BITS_PER_LONG == 32
```
Comment (tavip) [inline tools/lkl/include/lkl.h]: Hmm, I wonder if we need this even for non Android platforms. This would explain #360.

Comment (thehajime) [reply tools/lkl/include/lkl.h]: i don't have other 32bits environment than arm32 so, not sure if this is true or not.
do you see any issue on mingw32 ?

Comment (tavip) [reply tools/lkl/include/lkl.h]: That is the strange thing, I don't see any issue on either 32 or 64bit in the boot.c test. I thought that there might be some issues with libhijack but I disassemble it and the right number (0x19) is used there as well.

However, I noticed that we have a bug in asm-generic/unistd.h

```
#if (__LKL__BITS_PER_LONG == 32 || defined(__SYSCALL_COMPAT)) && \
     defined(__ARCH_WANT_SYSCALL_OFF_T)
...
#define __lkl__NR_fcntl 1052
```

Note that __ARCH_WANT_SYSCALL_OFF_T and __SYSCALL_COMPAT are not prefixed with LKL, which in certain build environments may be defined and set __lkl__NR_fcntl to an invalid value.

Can you confirm that this is the issue for Android?

**Comment by thehajime** [comment]
> Hope other tests are also fine (finger crossed).

it seems the following code block randomly failed over different tests.

```
echo "== boot command line tests =="
ans=$(LKL_HIJACK_DEBUG=1\
  LKL_HIJACK_BOOT_CMDLINE="mem=100M" ${hijack_script} ip ad)
if [ -z ${CROSS_COMPILE} ] ; then
echo "$ans" | grep "100752k"
elif [ "${CROSS_COMPILE}" = "arm-linux-androideabi-" ] ; then
echo "$ans" | grep "101424k"
elif [ "${CROSS_COMPILE}" = "aarch64-linux-android-" ] ; then
echo "$ans" | grep "100756k"
fi
```

I increased console output for the test in order to catch this issue in a future.

File: tools/lkl/include/lkl.h (hunk 5 above)
Comment (tavip) [reply tools/lkl/include/lkl.h]: Here is an quick band-aid patch that should fix the issue. With it applied, we should not need the above.

```
diff --git a/arch/lkl/scripts/headers_install.py b/arch/lkl/scripts/headers_install.py
index 6365da9..7b4ab22 100755
--- a/arch/lkl/scripts/headers_install.py
+++ b/arch/lkl/scripts/headers_install.py
@@ -165,6 +165,8 @@ p = re.compile("typedef\s+(struct|union)\s+\w*\s*{[^\\{\}]*}\W*(\w+)\s*;", re.M|
 find_ml_symbols(p, defines)
 defines.add("siginfo_t")
 defines.add("sigevent_t")
+defines.add("__ARCH_WANT_SYSCALL_OFF_T")
+defines.add("__SYSCALL_COMPAT")
 p = re.compile("struct\s+(\w+)\s*\{")
 find_symbols(p, structs)
 structs.add("iovec")
```

**Comment by thehajime** [comment]
Thanks for the review @tavip.

I will upgrade CircleCI instance to 4 instances and change to use ubuntu 14.04 (currently tested on ubuntu 12.04).
